# Generated by Django 4.2 on 2023-04-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamberlain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailitem',
            name='detail',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
