# Generated by Django 4.2 on 2023-04-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamberlain', '0002_detailitem_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='content',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
