# Generated by Django 4.2 on 2023-04-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamberlain', '0004_alter_attendance_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
